"""Compile CAR analytics into executable analyzers."""

from __future__ import annotations

import pprint
from pathlib import Path
from typing import Iterable

from jinja2 import Environment

from .loader import Analytic

_TEMPLATE = """# Auto-generated by trustmitre.analytics.compiler; do not edit.
from __future__ import annotations

from trustmitre.engine.dsl import CompiledAnalytic

ANALYTIC_SPEC = {{ spec | to_python }}


def build() -> CompiledAnalytic:
    return CompiledAnalytic.from_spec(ANALYTIC_SPEC)
"""

_env = Environment(trim_blocks=True, lstrip_blocks=True)
_env.filters["to_python"] = lambda value: pprint.pformat(value, width=100)
_template = _env.from_string(_TEMPLATE)


def _target_filename(analytic: Analytic) -> str:
    return analytic.analytic_id.lower().replace("-", "_") + ".py"


def compile_analytic(analytic: Analytic, destination: Path) -> Path:
    destination.mkdir(parents=True, exist_ok=True)
    target = destination / _target_filename(analytic)
    spec = {
        "analytic_id": analytic.analytic_id,
        "title": analytic.title,
        "description": analytic.description,
        "raw_text": analytic.raw_text,
        "operations": [
            {
                "kind": op.kind,
                "target": op.target,
                "expression": op.expression,
                "source": op.source,
            }
            for op in analytic.operations
        ],
    }
    rendered = _template.render(spec=spec)
    target.write_text(rendered, encoding="utf-8")
    return target


def compile_all(analytics: Iterable[Analytic], destination: Path) -> list[Path]:
    outputs: list[Path] = []
    for analytic in analytics:
        outputs.append(compile_analytic(analytic, destination))
    return outputs


__all__ = ["compile_analytic", "compile_all"]
